name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: AWS_REGION

jobs:
  deploy:
    name: TEST
    runs-on: ubuntu-latest
    environment: stage

    steps:
      - name: Test Env
        run: |
          echo ${{ secrets.TEST_SECRET }}
          echo $AWS_REGION
